Projeto.Web/Models/AutorModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations; //mapeamento

namespace Projeto.Web.Models
{
    public class AutorViewModelCadastro
    {
        [Required(ErrorMessage = "Por favor, informe o nome do autor.")]
        [MinLength(6, ErrorMessage = "Erro. Nome do Autor deve ter no minimo 6 caracteres.")]
        [MaxLength(50, ErrorMessage = "Erro. Nome do Autor deve ter no máximo 50 caracteres.")]
        [Display(Name = "Nome do Autor:")]
        public string Nome { get; set; }
    }

    public class AutorViewModelConsulta
    {
        public int IdAutor { get; set; }
        public string Nome { get; set; }
    }

    public class AutorViewModelEdicao
    {

        public int IdAutor { get; set; } //campo oculto..

        [Required(ErrorMessage = "Por favor, informe o nome do autor.")]
        [MinLength(6, ErrorMessage = "Erro. Nome do Autor deve ter no minimo 6 caracteres.")]
        [MaxLength(50, ErrorMessage = "Erro. Nome do Autor deve ter no máximo 50 caracteres.")]
        [Display(Name = "Nome do Autor:")]
        public string Nome { get; set; }
    }
}

Projeto.Web/Models/LivroModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Projeto.Entities.Types; //enum
using System.ComponentModel.DataAnnotations; //mapeamento..
using System.Web.Mvc;

namespace Projeto.Web.Models
{
    public class LivroViewModelCadastro
    {
        [Required(ErrorMessage = "Por favor, informe o titulo do livro.")]
        [Display(Name = "Titulo do Livro:")]
        public string Titulo { get; set; }

        [Required(ErrorMessage = "Por favor, informe o resumo do livro.")]
        [Display(Name = "Resumo do Livro:")]
        public string Resumo { get; set; }

        [Required(ErrorMessage = "Por favor, envie a foto do livro.")]
        [Display(Name = "Envie a Foto:")]
        public HttpPostedFileBase Foto { get; set; }

        [Required(ErrorMessage = "Por favor, selecione a categoria do livro.")]
        [Display(Name = "Selecione a Categoria:")]
        public Categoria Categoria { get; set; }

        [Required(ErrorMessage = "Por favor, selecione o autor do livro.")]
        [Display(Name = "Selecione o Autor:")]
        public List<SelectListItem> Autores { get; set; }
    }

    public class LivroViewModelConsulta
    {
        public int IdLivro { get; set; }
        public string Titulo { get; set; }
        public string Resumo { get; set; }
        public string Categoria { get; set; }
        public string Foto { get; set; }
        public string Autor { get; set; }
    }
}

Projeto.Web/Controllers/AutorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Projeto.Web.Models; //camada de modelo..
using Projeto.Application.Contracts; //interfaces
using Projeto.Entities; //entidades

namespace Projeto.Web.Controllers
{
    public class AutorController : Controller
    {        
        //atributo..
        private IAppServiceAutor appAutor; //null

        //construtor..
        public AutorController(IAppServiceAutor appAutor)
        {
            this.appAutor = appAutor;
        }


        // GET: /Autor/Cadastro
        public ActionResult Cadastro()
        {
            return View();
        }

        // GET: /Autor/Consulta
        public ActionResult Consulta()
        {
            //enviando a lista da model de consulta..
            return View(ListarAutores());
        }


        // GET: /Autor/CadastrarAutor
        [HttpPost]
        public ActionResult CadastrarAutor(AutorViewModelCadastro model)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    Autor a = new Autor();
                    a.Nome = model.Nome;

                    appAutor.Cadastrar(a); //aplicação..

                    ModelState.Clear();
                    ViewBag.Mensagem = "Autor " + a.Nome + ", cadastrado com sucesso.";
                }
                catch(Exception e)
                {
                    ViewBag.Mensagem = e.Message;
                }
            }

            return View("Cadastro"); //nome da página..
        }

        //método para retornar os autores cadastrados na base de dados..
        private List<AutorViewModelConsulta> ListarAutores()
        {
            var lista = new List<AutorViewModelConsulta>(); //lista vazia..
            try
            {
                //varrer os autores da base de dados..
                foreach(Autor a in appAutor.Listar())
                {
                    var model = new AutorViewModelConsulta();
                    model.IdAutor = a.IdAutor;
                    model.Nome = a.Nome;

                    lista.Add(model); //adicionando na lista..
                }
            }
            catch (Exception e)
            {
                //imprimir mensagem de erro..
                ViewBag.Mensagem = e.Message;
            }
            return lista; //retornar a lista...
        }
	}
}

Projeto.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Projeto.Web.Controllers
{
    public class HomeController : Controller
    {
        // GET: /Home/Index
        public ActionResult Index()
        {
            return View();
        }
	}
}

Projeto.Web/Controllers/LivroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Projeto.Web.Models; //camada de modelo..
using Projeto.Application.Contracts; //contratos

namespace Projeto.Web.Controllers
{
    public class LivroController : Controller
    {
        private IAppServiceLivro appLivro;

        public LivroController(IAppServiceLivro appLivro)
        {
            this.appLivro = appLivro;
        }

        // GET: /Livro/Cadastro
        public ActionResult Cadastro()
        {
            return View();
        }

        // GET: /Livro/Consulta
        public ActionResult Consulta()
        {
            return View();
        }
	}
}

Projeto.Web/Views/Autor/Cadastro.cshtml
@model Projeto.Web.Models.AutorViewModelCadastro

@{
    ViewBag.Title = "Cadastro";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("CadastrarAutor", "Autor", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        <h4>Cadastro de Autores</h4>
        <hr />

        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome)
                @Html.ValidationMessageFor(model => model.Nome)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar Autor" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @ViewBag.Mensagem
</div>

Projeto.Web/Views/Autor/Consulta.cshtml
@model IEnumerable<Projeto.Web.Models.AutorViewModelConsulta>

@{
    ViewBag.Title = "Consulta";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h4>Consulta de Autores</h4>

<p>
    @ViewBag.Mensagem
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdAutor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th></th>
    </tr>

@if(Model != null)
{ 
    foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdAutor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
    }
}

</table>

Projeto.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h4>Bem vindo Sistema</h4>

<p>
    Selecione a operação desejada:
</p>

<ul>
    <li> <a href="/Autor/Cadastro">Cadastrar Autores</a> </li>
    <li> <a href="/Autor/Consulta">Consultar Autores</a> </li>
</ul>

<ul>
    <li> <a href="/Livro/Cadastro">Cadastrar Livros</a> </li>
    <li> <a href="/Livro/Consulta">Consultar Livros</a> </li>
</ul>

Projeto.Web/Views/Livro/Cadastro.cshtml
@model Projeto.Web.Models.LivroViewModelCadastro

@{
    ViewBag.Title = "Cadastro";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        <h4>Cadastro de Livros</h4>
        <hr />

        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo)
                @Html.ValidationMessageFor(model => model.Titulo)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Resumo, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Resumo)
                @Html.ValidationMessageFor(model => model.Resumo)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Foto, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Foto" />
                @Html.ValidationMessageFor(model => model.Foto)
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar Livro" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @ViewBag.Mensagem
</div>

Projeto.Web/Views/Livro/Consulta.cshtml
@model IEnumerable<Projeto.Web.Models.LivroViewModelConsulta>

@{
    ViewBag.Title = "Consulta";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h4>Consulta de Livros</h4>

<p>
    @ViewBag.Mensagem
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdLivro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Titulo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Resumo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categoria)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Foto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Autor)
        </th>
        <th></th>
    </tr>

@if(Model != null)
{ 
    foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdLivro)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Titulo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Resumo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Categoria)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Foto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Autor)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
    }
}

</table>

Projeto.Web/Views/Shared/Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Layout</title>

    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />

</head>
<body class="container">

    <div class="well"> 
        <h3>Projeto Controle de Livros e Autores</h3>
        Aula de Asp.Net MVC - COTI Informatica
        <p>
            <a href="/Home/Index">Página inicial</a>
        </p>
    </div>

    <!-- Conteudo principal -->
    @RenderBody()

</body>
</html>